### ISSUE TITLE
Disccussion on the best approach to assign materials / constructions to faces

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-grasshopper-core#2]
See: https://github.com/ladybug-tools/honeybee-grasshopper-core/pull/1#discussion_r342123510

**Comment by chriswmackey** [comment]
We agreed that allowing people to input a string to call a construction or material from the library is good as long as we don't let people overwrite stuff in the library from the Grasshopper interface. 

So this is how we will implement it. The library will only be overiwrite-able by dropping in new IDF or JSON files into it (or editing existing files).

BTW, I also have some ideas to support the helpful functionality that the legacy library provided by allowing people to make a bunch of constructions or schedules in one Grasshopper file, internalize them as strings, and then add them to the library of another file like [what I did here](http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Full_Building_Energy_Simulation&slide=0&scale=7.5859684633523905&offset=-2384.3580007635514,-2065.3002698568807).  For [+]. I plan to support this type of workflow without touching the library, though.  Just allowing people to serialize any HBobject to a a dictionary and then to a string will allow them to create something they can internalize in a component and load up in another file as a full object that can be assigned to other objects. This also has the added benefit of also being write-able to a file (which advanced users may use to extend their library or use it to share their templates with others).
