### ISSUE TITLE
HB Label Faces error when connecting Face objects

### ISSUE THREAD

**Issue by kentakahas** [ladybug-tools/honeybee-grasshopper-core#271]
HB Label Faces returns an error (name 'face' is not defined) when connecting Face objects. 
Resolved when changing 'face' to 'obj' in lines 154 and 157.

**Comment by mostaphaRoudsari** [comment]
Thanks, @kentakahas - this is something that you could have used to create a PR. :)

Hi @chriswmackey, have you seen this comment?

**Comment by chriswmackey** [comment]
Ah, thanks for catching this and reporting it, @kentakahas . I'm sorry that it took me so long to see the issue you opened here since I'm used to having to scour the forum for bug reports.

I just pushed a fix here:
https://github.com/ladybug-tools/honeybee-grasshopper-core/pull/277
