### ISSUE TITLE
HB Face: Support mesh geometry as a first class citizen

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-grasshopper-core#3]
https://github.com/ladybug-tools/honeybee-grasshopper-core/pull/1#discussion_r342172558

**Comment by chriswmackey** [comment]
no need to have this as a discussion. I am implementing support for Meshes now.

**Comment by chriswmackey** [comment]
Done via https://github.com/chriswmackey/honeybee-grasshopper-core/commits/master !
