### ISSUE TITLE
Solve Adjacency: Use Interior Construction SubSet for Overriding Adjacent Faces Construction

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-grasshopper-core#6]
See https://github.com/ladybug-tools/honeybee-grasshopper-core/pull/1#discussion_r342187949

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I'm unclear on what there is to do for this issue.  All of the components to do this already exist between the PR you reference here and the PR that I am about to send to [honeybee-grasshopper-energy](https://github.com/chriswmackey/honeybee-grasshopper-energy).

**Comment by mostaphaRoudsari** [comment]
I have some comments about the workflow. It's not necessarily about the components. Let's discuss this when we get to it.

**Comment by chriswmackey** [comment]
Thinking this over further, I think we can group the constructions in "subsets" by boundary condition on the Grasshopper end but I don't think we should have new objects in honeybee-energy for `ExteriorSubset`, `GroundSubset` or `InteriorSubset`.  Instead, I think these should just be arrays of constructions.

The main reason for it is that, if people think of the `InteriorSubset` as a contained object with all of the constructions needed to describe all interior constructions, it negatively impacts workflows where people want to start from an existing `ConstructionSet` and only edit a single interior construction.  It's a little easier to say that this `InteriorSubset` is an array and, if one of the values in the array is `None`, then the construction in that index will not be overwritten in the base `ConstructionSet` that we are starting from.

**Comment by chriswmackey** [comment]
The same logic applies to how the Interior component would work with "HB Solve Adjacency". If someone has not plugged in a construction in the `interior_ceiling` slot and only the `interior_wall` slot, the `interior_ceiling` isn't going to get overwritten within the "HB Solve Adjacency" component with whatever the generic default ceiling construction is.

**Comment by chriswmackey** [comment]
This one is done!
