### ISSUE TITLE
Consider Separating All Extension Attributes Out of Core Components

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-grasshopper-core#9]
The main issue here is that we have been good about separating the core of honeybee from each of the extensions (energy, radiance) in the way that we have set up the Honeybee object schemas, laid out the Python packages, and organized the repos/tabs of honeybee components. Up to this point, we have not regretted this separation and, in many cases, it has sped up our development process, allowed others to more easily contribute to the domain of knowledge that they know best, and will enable better use of micro services for Pollination.  However, we now face a different question than what is the most practical for us developers, contributors, etc. and we have to also consider what is most piratical for the users of Grasshopper components.

Specifically, the question is should we separate out a component like this:
![image](https://user-images.githubusercontent.com/5567574/68547347-74faae80-03ae-11ea-9612-86111cb2f08f.png)
... into this:
![image](https://user-images.githubusercontent.com/5567574/68547363-b9864a00-03ae-11ea-8211-7ba273bbc626.png)

... and, by extension take a component like this:
![image](https://user-images.githubusercontent.com/5567574/68547391-39141900-03af-11ea-964a-3d00076e43dc.png)
... and remove the ability to assign extension attributes on it:
![image](https://user-images.githubusercontent.com/5567574/68547395-429d8100-03af-11ea-814b-c39ee6ebf14c.png)

I think @mostaphaRoudsari already knows I feel this is a case were "practicality beats purity" but I wanted to lay out a list of pros and cons so that we can have a discussion about it and make the right decision. Recognizing that I am biased, I would encourage others to add things that I am missing, especially to this first list:

**PROS for Separating All Extension Attributes Out of Core Components:**
1. It makes the components cleaner if someone wants to install just honeybee Radiance or honeybee Energy (without comfort mapping). Right now, the inputs for `ep_constr_` on the "HB Face" component do not work if someone only installs honeybee-radiance and this "feels" unclean. But I don't think we will be able to make a good decision on this until we find a user who is only interested in installing honeybee Radiance without Energy and ask them if the extra unusable input is an issue or annoying to them.
2. It makes more work for us (developers) to support "Node to Code" workflows, which we know will become important for iterative workflows in Pollination Cloud. For such workflows, we need a clear boundary in Grasshopper scripts where someone crosses over from native Grasshopper/Rhino world into Ladybug + Honeybee component world.  In theory, we could say that the honeybee core components are part of the native Grasshopper/Rhino world and all components that add extension attributes after this are compile-able into a single python script (since all their inputs for extensions are non-geometric).  However, it is also possible for us to put the boundary between the two worlds elsewhere (like before the honeybee-core components by having people input ladybug_geometry instead of Rhino geometry into these components). Lastly, we could put the boundary inside the code of the core components, separating out the part where geometry translation happens from everything after it.

**CONS for Separating All Extension Attributes Out of Core Components:**
1. It removes important functionality like that described in the solve adjacency component above. It also removes the ability to to assign glazing constructions to newly-generated Apertures in the "Aperture-by-Ratio" component along with several other components that automate the creation of new Honeybee core geometry objects.
2. It makes it more likely for users to just take the default extension attributes and not assign vital properties like ConstructionSets and ProgramTypes to Honeybee Rooms . The way it is now, people will be aware of these key properties and may be more likely to change them (as they should):
![image](https://user-images.githubusercontent.com/5567574/68547487-16cecb00-03b0-11ea-9a1b-f4d2dc0d0003.png)
3. It requires users to put more components on the canvass in order to create a Model, especially when creating combination radiance + energy models. This has a few repercussions (all of which are not serious but they should be a part of the decision).  Specifically, more components means a slightly higher learning curve for new users (especially those with little experience in visual scripting).  Just think about teaching a workshop where we need to drop an extra extension component for every core component we use. It also might become annoying to users who constantly build new models and find themselves having to drop 3 components on the canvass for each object instead of one.  With this said, the "annoyance" here probably isn't more than the annoyance for a user wanting to install only honeybee-radiance and who has to deal with unusable honeybee-energy inputs (point 1 under the Pros section).

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, thank you for drafting this issue. I think the issue with the solve adjacency can also be addressed but I think before trying to figure that out it is better to get some feedback from others.

To get that started, I'm tagging a number of users / developers who have forked ladybug-legacy repository! 😅

👋Hi @ayezioro, @devngc, @Vyrwn, @MingboPeng, @vhoangTS, @Omidmr, what are your thoughts on this?

## Short description

Honeybee daylight and energy extensions are now separated from honeybee-core. This means one can install only daylight or energy extensions if desired.

The question is about how should this decision affect the design of the components?

One approach is to keep the inputs for each extension and raise an error if one tries to use them w/o installing the extensions. This is very similar to the legacy components.

![image](https://user-images.githubusercontent.com/5567574/68547347-74faae80-03ae-11ea-9612-86111cb2f08f.png)

Another one is to separate them from the core component and put them in new components that gets installed with the extensions itself. The first component creates the honeybee face. The following components needs to be used to modify the properties:

![image](https://user-images.githubusercontent.com/5567574/68547363-b9864a00-03ae-11ea-8211-7ba273bbc626.png)

@chriswmackey has documented this in more details 👆. What are you thoughts? Which one do you prefer and why?

**Comment by ayezioro** [comment]
Hi @mostaphaRoudsari and @chriswmackey,
Hmmm ... From my side i can say that i look more at the Cons than at the Pros. As mentioned, the amount of components to be inserted might be incredible high. Not sure if this will make the debugging easier or more difficult, for the users.
Another con that can be said is regarding the existing users, that are not just a few. Usually new versions of software don't change the UI completely. Something like this can imply having to learn or develop new flow works. I don't like this so much.
As i see the Pros are more on the developers side, which is important, but not sure that more than the user's POV.

I want to suggest, maybe, a third option which will represent some more work for the developers. It is creating clusters of functions. They will contain the individual receipts but can allow to concentrate the whole package of calculation. I've seen something like this with the [Urbano plugin](https://www.urbano.io). They created templates than when inserted the expand (see the animated gif around the middle of the site, scrolling down).

Will be interesting to hear others, since looks like things are at a critical point right now.

Best regards,
-A.

**Comment by vhoangTS** [comment]
Hi @mostaphaRoudsari, hi @chriswmackey and all,
Thank you for tagging me in this discussion!

Personally I prefer having less components (cleaner canvas, in general more straight forward debugging). Thus for me it makes more sense to maintain the previous design with inputs for both Daylight & Energy in one component and the user can choose which one to use depending on their needs. 
Regarding point 1 of the Pros for Seperation, back at Transsolar we only work with the Daylight part of Honeybee and honestly I didn't find it annoying at all to see the EP inputs in the same component. On contrary, it acctually illustrates better the advantage that you can do both Daylight & Energy simulation with Honeybee and how the two simulations share same initial input models. Splitting the components would lead to "same same but different" initial workflow and sometime it is hard to explain this to new users.

Hope that helps,
V

**Comment by MingboPeng** [comment]
I am all for the minimum components, minimum inputs, but without losing abilities of setting ALL details. 
Totally agree with @ayezioro @vhoangTS for the benefits of less components. One more point to add is less components saves RAMs as well.
For minimum inputs, I would even suggest combining "boundary condition" with "ep_constr" to one input as "EP_Prop_". Users can add all energy related surface properties to this one (ONLY ONE) input. 
![image](https://user-images.githubusercontent.com/9031066/68632055-428aa780-04bb-11ea-9812-e7327a52169f.png)

**Comment by mostaphaRoudsari** [comment]
@ayezioro, @vhoangTS and @MingboPeng, thank you for providing quick feedback. I think the direction is clear.

**Comment by chriswmackey** [comment]
Shall we close this issue, then, @mostaphaRoudsari ?
